# Generated by Django 3.1.8 on 2021-05-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid until')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('absolute', 'Absolute')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Is discount valid only with included code', max_length=30, verbose_name='Code')),
                ('max_usage', models.IntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_coupons.offer')),
            ],
            options={
                'unique_together': {('offer', 'code')},
            },
        ),
    ]
