# Generated by Django 3.1.8 on 2021-05-15 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.FloatField(default=1, help_text='Percent/Absolute discount value.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Is discount valid only with included code', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid from'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together=set(),
        ),
    ]
